// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANSZXxBh_6znrpjDelaoYwlkBVY4u_iSU',
    appId: '1:946364747353:web:cfc2f54090d7e09550eb48',
    messagingSenderId: '946364747353',
    projectId: 'education-institution-2af19',
    authDomain: 'education-institution-2af19.firebaseapp.com',
    storageBucket: 'education-institution-2af19.appspot.com',
    measurementId: 'G-NXJ0KT7JE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwCc2oh6wxD87-wdAfkwkHvjrOumDDuAo',
    appId: '1:946364747353:android:9e79574e07caf6c750eb48',
    messagingSenderId: '946364747353',
    projectId: 'education-institution-2af19',
    storageBucket: 'education-institution-2af19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdiTgym5rVAqIJu04euX1FSUNhOlVbULg',
    appId: '1:946364747353:ios:7e705d06cffcc40b50eb48',
    messagingSenderId: '946364747353',
    projectId: 'education-institution-2af19',
    storageBucket: 'education-institution-2af19.appspot.com',
    iosBundleId: 'com.example.educationInstitution',
  );
}
